version: "3.8"

services:

  db:
    image: postgres:15
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_HOST_AUTH_METHOD: trust
    networks:
      - app-network
    volumes:
      - db-data:/var/lib/postgresql/data

  redis:
    image: redis:alpine
    networks:
      - app-network

  worker:
    image: docker/example-voting-app-worker
    depends_on:
      - db
      - redis
    networks:
      - app-network

  vote:
    image: docker/example-voting-app-vote
    ports:
      - 5000:80
    depends_on:
      - redis
    networks:
      - app-network

  result:
    image: docker/example-voting-app-result
    ports:
      - 5001:80
    depends_on:
      - db
    networks:
      - app-network

volumes:
  db-data:

networks:
  app-network:
