apiVersion: apps/v1
kind: Deployment
metadata:
  name: widget-controller
spec:
  replicas: 1
  selector:
    matchLabels:
      app: widget-controller
  template:
    metadata:
      labels:
        app: widget-controller
    spec:
      serviceAccountName: widget-controller-sa
      containers:
      - name: widget-controller
        image: nagabhushanamn/widget-controller:0.1
        imagePullPolicy: Always
        command: ["python3"]
        args: ["/app/widget-controller.py"]
        ports:
        - containerPort: 8080
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 5
        readinessProbe:
          httpGet:
            path: /healthz
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5
        resources:
          limits:
            cpu: "500m"
            memory: "512Mi"
          requests:
            cpu: "100m"
            memory: "256Mi"
