apiVersion: v1
kind: ServiceAccount
metadata:
  name: widget-controller-sa
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: widget-controller-role
  namespace: default
rules:
  - apiGroups: ["example.com"]
    resources: ["widgets"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: widget-controller-rolebinding
  namespace: default
subjects:
  - kind: ServiceAccount
    name: widget-controller-sa
    namespace: default
roleRef:
  kind: Role
  name: widget-controller-role
  apiGroup: rbac.authorization.k8s.io
