apiVersion: v1
kind: Pod
metadata:
  name: java-web-service-pod-1
spec:
  nodeName: my-k8s-cluster-worker
  containers:
  - name: java-web-service-container
    image: docker.io/nagabhushanamn/java-web-service:v1.2
    volumeMounts:
    - mountPath: /app/data
      name: my-log-volume
  volumes:
  - name: my-log-volume
    persistentVolumeClaim:
      claimName: my-log-pvc

---

apiVersion: v1
kind: Pod
metadata:
  name: java-web-service-pod-2
spec:
  nodeName: my-k8s-cluster-worker2
  containers:
  - name: java-web-service-container
    image: docker.io/nagabhushanamn/java-web-service:v1.2
    volumeMounts:
    - mountPath: /app/data
      name: my-log-volume
  volumes:
  - name: my-log-volume
    persistentVolumeClaim:
      claimName: my-log-pvc
    
    