apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cluster-read-only
rules:
  - apiGroups: [""]  # "" = Core API group
    resources: ["pods", "services", "nodes"]
    verbs: ["get", "list", "watch"]