
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: cluster-read-only-binding
subjects:
  - kind: User
    name: user1  # This must match the certificate CN (TLS authentication)
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: cluster-read-only  # Must match the ClusterRole name
  apiGroup: rbac.authorization.k8s.io
