apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod-1
  labels:
<<<<<<< HEAD
    foo: bar
    app: nginx
    envi: prod
=======
    foo: foo
    app: nginx
    env: prod
>>>>>>> 7d6a1ca (schedule pods)
spec:
  containers:
  - image: nginx:1.11.7
    name: nginx-container

---

apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod-2
  labels:
<<<<<<< HEAD
    foo: bar
    app: nginx
    envi: prod
=======
    foo: foo
    app: nginx
    env: prod
>>>>>>> 7d6a1ca (schedule pods)
spec:
  containers:
  - image: nginx:1.11.7
    name: nginx-container

---

apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod-3
  labels:
<<<<<<< HEAD
    foo: bar
    app: nginx
    envi: prod
=======
    foo: foo
    app: nginx
    env: prod
>>>>>>> 7d6a1ca (schedule pods)
spec:
  containers:
  - image: nginx:1.11.7
    name: nginx-container
<<<<<<< HEAD

=======
>>>>>>> 7d6a1ca (schedule pods)
