apiVersion: v1
kind: ReplicationController
metadata:
  name: nginx-rc
  labels:
    app: nginx
    type: front-end
spec:
  replicas: 1
  selector:
    app: nginx  
    type : front-end 
  template:
    metadata:
      name: nginx-pod
      labels:
        app: nginx
        type: front-end
    spec:
      containers:
      - image: nginx
        name: nginx-container
  