apiVersion: v1
kind: Pod
metadata:
  name: manual-scheduled-pod
spec:
  nodeName: my-k8s-cluster-worker
  containers:
  - name: busybox
    image: busybox
    command: ["sh", "-c", "echo 'Manually scheduled' && sleep 3600"]
