apiVersion: v1
kind: Pod
metadata:
  name: node-selector-pod
spec:
  nodeSelector:
    size: medium  # Pod will only run on nodes labeled with "size=large"
  containers:
  - name: nginx
    image: nginx

