

apiVersion: v1
kind: Pod
metadata:
  name: pod-anti-affinity-pod-1
  labels:
    app: nginx
spec:
  nodeName: my-k8s-cluster-worker
  containers:
  - name: nginx
    image: nginx

---


apiVersion: v1
kind: Pod
metadata:
  name: pod-anti-affinity-pod-2
  labels:
    app: nginx
spec:
  nodeName: my-k8s-cluster-worker2
  containers:
  - name: nginx
    image: nginx

---


apiVersion: v1
kind: Pod
metadata:
  name: pod-anti-affinity-pod-3
  labels:
    app: nginx
spec:
  nodeName: my-k8s-cluster-worker3
  containers:
  - name: nginx
    image: nginx

---


apiVersion: v1
kind: Pod
metadata:
  name: pod-anti-affinity-pod-4
spec:
  affinity:
    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        - labelSelector:
            matchLabels:
              app: nginx
          topologyKey: "kubernetes.io/hostname"
  containers:
  - name: nginx
    image: nginx
