apiVersion: v1
kind: Pod
metadata:
  name: taint-toleration-pod
spec:
  tolerations:
  - key: "kafka"
    operator: "Equal"
    value: "true"
    effect: "NoSchedule"
  containers:
  - name: nginx
    image: nginx
